"""Build a larger Chinese SFT corpus from public datasets.

Default sources:
    - m-a-p/COIG-CQIA
    - YeungNLP/firefly-train-1.1M
    - Hello-SimpleAI/HC3-Chinese
    - local seed QA generated by scripts.prepare_sft_qa_data

BELLE is optional because its GPL-3.0 license may be too restrictive for some
projects.

Examples:
    python -B scripts/prepare_public_sft_data.py --target-size 150000 --force
    python -B scripts/prepare_public_sft_data.py --target-size 200000 --include-belle --force
    python -B scripts/prepare_public_sft_data.py --dry-run
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.prepare_sft_qa_data import built_in_rows, write_jsonl


CHINESE_RE = re.compile(r"[\u4e00-\u9fff]")
SPACE_RE = re.compile(r"\s+")
BAD_RE = re.compile(r"(彩票|博彩|裸聊|成人视频|代孕|六合彩|网赚)")
MOJIBAKE_RE = re.compile(r"(\ufffd|锟|閻|鐗|涓|绋|鏉|娑|搢)")


@dataclass(frozen=True)
class SourceSpec:
    name: str
    dataset: str
    weight: float
    config: str | None = None
    split: str = "train"
    data_files: str | list[str] | None = None
    optional: bool = False


DEFAULT_SOURCES = [
    SourceSpec("coig_cqia_wiki", "m-a-p/COIG-CQIA", config="wiki", weight=20),
    SourceSpec("coig_cqia_zhihu", "m-a-p/COIG-CQIA", config="zhihu", weight=15),
    SourceSpec("coig_cqia_exam", "m-a-p/COIG-CQIA", config="exam", weight=10),
    SourceSpec("firefly", "YeungNLP/firefly-train-1.1M", weight=30),
]

BELLE_SOURCE = SourceSpec("belle_2m", "BelleGroup/train_2M_CN", weight=25, optional=True)


PROMPT_KEYS = [
    "prompt",
    "instruction",
    "question",
    "query",
    "input",
    "human",
    "user",
]

ANSWER_KEYS = [
    "answer",
    "output",
    "response",
    "target",
    "assistant",
    "completion",
]


def resolve_path(value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else PROJECT_ROOT / path


def clean_text(text: str) -> str:
    text = text.replace("\u3000", " ")
    text = SPACE_RE.sub(" ", text)
    return text.strip()


def chinese_ratio(text: str) -> float:
    return len(CHINESE_RE.findall(text)) / max(len(text), 1)


def first_text(row: dict[str, Any], keys: Iterable[str]) -> str:
    for key in keys:
        value = row.get(key)
        if isinstance(value, str) and value.strip():
            return value
        if isinstance(value, list):
            parts = [item for item in value if isinstance(item, str) and item.strip()]
            if parts:
                return "\n".join(parts)
    return ""


def normalize_messages(row: dict[str, Any]) -> dict[str, str] | None:
    messages = row.get("messages") or row.get("conversations")
    if not isinstance(messages, list):
        return None

    user_parts: list[str] = []
    assistant_parts: list[str] = []
    for item in messages:
        if not isinstance(item, dict):
            continue
        role = str(item.get("role") or item.get("from") or "").lower()
        content = item.get("content") or item.get("value")
        if not isinstance(content, str) or not content.strip():
            continue
        if role in {"user", "human", "instruction"}:
            user_parts.append(content.strip())
        elif role in {"assistant", "gpt", "bot"}:
            assistant_parts.append(content.strip())

    if not user_parts or not assistant_parts:
        return None
    return {"prompt": "\n".join(user_parts[-2:]), "answer": assistant_parts[-1]}


def normalize_hc3(row: dict[str, Any]) -> dict[str, str] | None:
    question = row.get("question")
    if not isinstance(question, str) or not question.strip():
        return None
    human_answers = row.get("human_answers")
    chatgpt_answers = row.get("chatgpt_answers")
    answer = ""
    if isinstance(human_answers, list):
        answer = next((item for item in human_answers if isinstance(item, str) and item.strip()), "")
    if not answer and isinstance(chatgpt_answers, list):
        answer = next((item for item in chatgpt_answers if isinstance(item, str) and item.strip()), "")
    if not answer:
        return None
    return {"prompt": question, "answer": answer}


def normalize_row(row: Any) -> dict[str, str] | None:
    if not isinstance(row, dict):
        return None

    for normalizer in (normalize_messages, normalize_hc3):
        normalized = normalizer(row)
        if normalized is not None:
            return normalized

    instruction = row.get("instruction")
    input_text = row.get("input")
    output = row.get("output")
    if isinstance(instruction, str) and isinstance(output, str):
        prompt = instruction.strip()
        if isinstance(input_text, str) and input_text.strip():
            prompt = prompt + "\n" + input_text.strip()
        return {"prompt": prompt, "answer": output.strip()}

    prompt = first_text(row, PROMPT_KEYS)
    answer = first_text(row, ANSWER_KEYS)
    if not prompt or not answer:
        return None
    return {"prompt": prompt, "answer": answer}


def is_good_sft_row(row: dict[str, str], args: argparse.Namespace) -> bool:
    prompt = clean_text(row["prompt"])
    answer = clean_text(row["answer"])
    if len(prompt) < args.min_prompt_chars or len(prompt) > args.max_prompt_chars:
        return False
    if len(answer) < args.min_answer_chars or len(answer) > args.max_answer_chars:
        return False
    joined = prompt + "\n" + answer
    if chinese_ratio(joined) < args.min_chinese_ratio:
        return False
    if BAD_RE.search(joined) or MOJIBAKE_RE.search(joined):
        return False
    if answer.startswith(prompt) and len(prompt) > 20:
        return False
    return True


def row_digest(row: dict[str, str]) -> str:
    return hashlib.blake2b((row["prompt"] + "\n" + row["answer"]).encode("utf-8"), digest_size=16).hexdigest()


def load_stream(source: SourceSpec, cache_dir: str | None):
    try:
        from datasets import load_dataset
    except ImportError as exc:
        raise ImportError("Please install datasets: pip install datasets") from exc

    kwargs: dict[str, Any] = {"streaming": True, "split": source.split}
    if cache_dir:
        kwargs["cache_dir"] = str(resolve_path(cache_dir))
    if source.data_files is not None:
        kwargs["data_files"] = source.data_files
    if source.config is not None:
        return load_dataset(source.dataset, source.config, **kwargs)
    return load_dataset(source.dataset, **kwargs)


def sample_source(source: SourceSpec, quota: int, args: argparse.Namespace) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    rejected = 0
    try:
        stream = load_stream(source, args.cache_dir)
        print(f"Streaming {source.name}: {source.dataset} target={quota}")
        for raw in stream:
            normalized = normalize_row(raw)
            if normalized is None:
                rejected += 1
                continue
            normalized = {
                "prompt": clean_text(normalized["prompt"]),
                "answer": clean_text(normalized["answer"]),
            }
            if not is_good_sft_row(normalized, args):
                rejected += 1
                continue
            rows.append(normalized)
            if len(rows) % args.log_every == 0:
                print(f"  {source.name}: accepted={len(rows)}, rejected={rejected}")
            if len(rows) >= quota:
                break
    except Exception as exc:  # noqa: BLE001 - keep dataset fallback easy during experimentation.
        if source.optional or args.skip_failed_sources:
            print(f"Warning: skip source {source.name}: {exc}")
            return rows
        raise

    print(f"Finished {source.name}: accepted={len(rows)}, rejected={rejected}")
    return rows


def split_rows(rows: list[dict[str, str]], valid_ratio: float, rng: random.Random) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    rng.shuffle(rows)
    valid_size = max(1, int(len(rows) * valid_ratio))
    return rows[valid_size:], rows[:valid_size]


def compute_quotas(sources: list[SourceSpec], target_size: int, seed_size: int) -> dict[str, int]:
    dataset_target = max(0, target_size - seed_size)
    total_weight = sum(source.weight for source in sources)
    quotas: dict[str, int] = {}
    assigned = 0
    for source in sources:
        quota = int(dataset_target * source.weight / total_weight)
        quotas[source.name] = quota
        assigned += quota
    if sources:
        quotas[sources[0].name] += dataset_target - assigned
    return quotas


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--train-output", default="data/sft/sft_train.jsonl")
    parser.add_argument("--valid-output", default="data/sft/sft_valid.jsonl")
    parser.add_argument("--raw-output", default="data/sft/public_sft_all.jsonl")
    parser.add_argument("--target-size", type=int, default=150000)
    parser.add_argument("--seed-size", type=int, default=10000)
    parser.add_argument("--valid-ratio", type=float, default=0.05)
    parser.add_argument("--cache-dir", default=".cache/huggingface")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--include-belle", action="store_true")
    parser.add_argument("--skip-failed-sources", action="store_true")
    parser.add_argument("--min-prompt-chars", type=int, default=4)
    parser.add_argument("--max-prompt-chars", type=int, default=1200)
    parser.add_argument("--min-answer-chars", type=int, default=8)
    parser.add_argument("--max-answer-chars", type=int, default=1800)
    parser.add_argument("--min-chinese-ratio", type=float, default=0.25)
    parser.add_argument("--log-every", type=int, default=5000)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not 0.0 < args.valid_ratio < 0.5:
        raise ValueError(f"valid-ratio must be between 0 and 0.5, got {args.valid_ratio}.")

    outputs = [resolve_path(args.train_output), resolve_path(args.valid_output), resolve_path(args.raw_output)]
    for path in outputs:
        if path.exists() and path.stat().st_size > 0 and not args.force:
            raise FileExistsError(f"Output exists, pass --force to overwrite: {path}")

    rng = random.Random(args.seed)
    sources = list(DEFAULT_SOURCES)
    if args.include_belle:
        sources.append(BELLE_SOURCE)

    seed_rows = built_in_rows(rng, min(args.seed_size, args.target_size))
    quotas = compute_quotas(sources, args.target_size, len(seed_rows))
    print("SFT source quotas:")
    print(f"  seed_qa: {len(seed_rows)}")
    for source in sources:
        print(f"  {source.name}: {quotas[source.name]}")
    if args.dry_run:
        return

    all_rows = list(seed_rows)
    for source in sources:
        if quotas[source.name] <= 0:
            continue
        all_rows.extend(sample_source(source, quotas[source.name], args))

    deduped: list[dict[str, str]] = []
    seen: set[str] = set()
    for row in all_rows:
        key = row_digest(row)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(row)

    train_rows, valid_rows = split_rows(deduped, args.valid_ratio, rng)
    print(f"Final SFT rows: train={len(train_rows)}, valid={len(valid_rows)}, total={len(deduped)}")

    raw_output = resolve_path(args.raw_output)
    write_jsonl(raw_output, deduped)
    write_jsonl(resolve_path(args.train_output), train_rows)
    write_jsonl(resolve_path(args.valid_output), valid_rows)
    print(f"Wrote raw: {raw_output}")
    print(f"Wrote train: {resolve_path(args.train_output)}")
    print(f"Wrote valid: {resolve_path(args.valid_output)}")


if __name__ == "__main__":
    main()
